version: 3
services:
  db:
    image: mysql:8.0.18
    network: host
  user-service:
    build: ./user
    ports:
      - 9000:9000
    depends_on:
      - db
    network: host
  comment-service:
    build: ./comment
    ports:
      - 9001:9001
    depends_on:
      -db
    network: host