version: '3'
services:
  db:
    image: mysql:8.0.18
    network: host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  user-service:
    build: ./user
    ports:
      - 9000:9000
    depends_on:
      - db
    network: host
  comment-service:
    build: ./comment
    ports:
      - 9001:9001
    depends_on:
      - db
    network: host

# Names our volume
volumes:
  my-db: